import { JarvisCommand, CourseData, GeneratedHtmlApp } from '../types';

export const DEFAULT_API_KEY = 'AIzaSyAkkW-f2icBwpKBFqyoTQ14A15nI8IProU';
const PRIMARY_MODEL = 'gemini-2.5-flash';
const FALLBACK_MODEL = 'gemini-1.5-flash';

export function getEffectiveApiKey(): string {
  return localStorage.getItem('CUSTOM_GEMINI_API_KEY') || 
         (process.env.GEMINI_API_KEY as string) || 
         DEFAULT_API_KEY;
}

export function setCustomApiKey(key: string) {
  if (key.trim()) {
    localStorage.setItem('CUSTOM_GEMINI_API_KEY', key.trim());
  } else {
    localStorage.removeItem('CUSTOM_GEMINI_API_KEY');
  }
}

async function callGeminiApi(prompt: string, systemInstruction?: string, model: string = PRIMARY_MODEL): Promise<string> {
  const effectiveKey = getEffectiveApiKey();
  if (!effectiveKey) {
    throw new Error('Gemini API Key is missing. Please configure GEMINI_API_KEY in Secrets or enter it in settings.');
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${effectiveKey}`;
  
  const body: any = {
    contents: [
      {
        parts: [{ text: prompt }]
      }
    ],
    generationConfig: {
      temperature: 0.7,
      topP: 0.95,
      maxOutputTokens: 8192
    }
  };

  if (systemInstruction) {
    body.systemInstruction = {
      parts: [{ text: systemInstruction }]
    };
  }

  try {
    const res = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });

    if (!res.ok) {
      const errText = await res.text();
      // Try fallback model if 404 or preview not available
      if (model === PRIMARY_MODEL && (res.status === 404 || res.status === 400)) {
        return callGeminiApi(prompt, systemInstruction, FALLBACK_MODEL);
      }
      throw new Error(`Gemini API error (${res.status}): ${errText}`);
    }

    const data = await res.json();
    const candidateText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!candidateText) {
      throw new Error('No response text generated by Gemini');
    }
    return candidateText;
  } catch (error: any) {
    if (model === PRIMARY_MODEL) {
      console.warn(`Primary model ${PRIMARY_MODEL} failed, attempting fallback to ${FALLBACK_MODEL}`, error);
      return callGeminiApi(prompt, systemInstruction, FALLBACK_MODEL);
    }
    throw error;
  }
}

export async function parseJarvisCommand(userInput: string): Promise<JarvisCommand> {
  const systemPrompt = `You are JARVIS, Tony Stark's ultra-intelligent AI Assistant and Android Phone Controller.
The user speaks in Urdu (اردو), Roman Urdu, or English.
Analyze the user command and determine the exact action to execute on their smartphone.
The possible actions are:
1. 'SEND_SMS': User wants to send an SMS or text message. Extract phoneNumber/recipient and message body.
2. 'OPEN_APP': User wants to open or launch an application on their phone (e.g. WhatsApp, YouTube, Chrome, Camera, Instagram, TikTok, Settings, Gallery, Calculator).
3. 'INSTALL_APP': User wants to download/install an app from Google Play Store. Extract appName.
4. 'PLAY_SONG': User wants to play a song, music, naat, qawwali, or video. Extract songTitle.
5. 'GENERATE_HTML': User wants to build, code, or generate an HTML app or webpage. Extract htmlTopic.
6. 'DOWNLOAD_PDF': User wants to create or download a PDF report, document, or notes. Extract pdfTitle and pdfContent outline.
7. 'CREATE_COURSE': User wants to create a learning course or syllabus. Extract courseTopic and courseLevel.
8. 'CREATE_PROMPT': User wants to generate or engineer a prompt. Extract promptSubject and promptCategory.
9. 'GENERAL_CHAT': General question, greetings, status check, or conversation.

Return ONLY a valid raw JSON object (without markdown code blocks):
{
  "action": "ACTION_NAME",
  "query": "${userInput.replace(/"/g, '\\"')}",
  "parameters": {
    "phoneNumber": "number or contact name if any",
    "message": "message body to send",
    "appName": "name of the app to open or install",
    "songTitle": "title of song/music",
    "htmlTopic": "topic of the HTML app",
    "pdfTitle": "title for PDF document",
    "pdfContent": "detailed text/content to include in PDF",
    "courseTopic": "topic of the course",
    "courseLevel": "Beginner/Intermediate/Advanced",
    "promptSubject": "topic of prompt",
    "promptCategory": "Coding/Image/Marketing/Writing"
  },
  "explanationUrdu": "اردو میں مختصر اور پروقار جواب کہ آپ کیا عمل کر رہے ہیں",
  "explanationEnglish": "Polite crisp British JARVIS response acknowledging the action"
}`;

  try {
    const rawText = await callGeminiApi(userInput, systemPrompt);
    const cleaned = rawText.replace(/```json/g, '').replace(/```/g, '').trim();
    const parsed = JSON.parse(cleaned);
    return parsed;
  } catch (err) {
    console.error('Failed to parse command with Gemini:', err);
    // Local smart heuristic fallback
    const lower = userInput.toLowerCase();
    if (lower.includes('sms') || lower.includes('میسج') || lower.includes('سینڈ') || lower.includes('message')) {
      return {
        action: 'SEND_SMS',
        query: userInput,
        parameters: { phoneNumber: '', message: userInput },
        explanationUrdu: 'سر، ایس ایم ایس کھولنے کی تیاری ہو رہی ہے۔',
        explanationEnglish: 'Preparing SMS dispatch protocol, Sir.'
      };
    } else if (lower.includes('open') || lower.includes('کھولو') || lower.includes('اوپن')) {
      const appName = userInput.replace(/open|اوپن|کھولو/gi, '').trim();
      return {
        action: 'OPEN_APP',
        query: userInput,
        parameters: { appName: appName || 'App' },
        explanationUrdu: `سر، ${appName} ایپ لانچ کی جا رہی ہے۔`,
        explanationEnglish: `Opening ${appName} immediately, Sir.`
      };
    } else if (lower.includes('play store') || lower.includes('انسٹال') || lower.includes('install') || lower.includes('ڈاؤنلوڈ ایپ')) {
      const appName = userInput.replace(/play store|install|انسٹال|ڈاؤنلوڈ/gi, '').trim();
      return {
        action: 'INSTALL_APP',
        query: userInput,
        parameters: { appName: appName || 'App' },
        explanationUrdu: `سر، پلے اسٹور پر ${appName} سرچ کی جا رہی ہے۔`,
        explanationEnglish: `Locating ${appName} on Google Play Store, Sir.`
      };
    } else if (lower.includes('song') || lower.includes('گانا') || lower.includes('سونگ') || lower.includes('play') || lower.includes('چلاؤ')) {
      const songTitle = userInput.replace(/song|play|گانا|چلاؤ|سونگ/gi, '').trim();
      return {
        action: 'PLAY_SONG',
        query: userInput,
        parameters: { songTitle: songTitle || 'Music' },
        explanationUrdu: `سر، ${songTitle} گانا چلایا جا رہا ہے۔`,
        explanationEnglish: `Playing audio track: ${songTitle}, Sir.`
      };
    } else if (lower.includes('html') || lower.includes('ایچ ٹی ایم ایل') || lower.includes('ویب')) {
      return {
        action: 'GENERATE_HTML',
        query: userInput,
        parameters: { htmlTopic: userInput },
        explanationUrdu: 'سر، ایچ ٹی ایم ایل کوڈ اور ایپ تیار کی جا رہی ہے۔',
        explanationEnglish: 'Generating standalone HTML application, Sir.'
      };
    } else if (lower.includes('pdf') || lower.includes('پی ڈی ایف')) {
      return {
        action: 'DOWNLOAD_PDF',
        query: userInput,
        parameters: { pdfTitle: 'JARVIS Generated Document', pdfContent: userInput },
        explanationUrdu: 'سر، پی ڈی ایف دستاویز تیار کر کے ڈاؤن لوڈ کی جا رہی ہے۔',
        explanationEnglish: 'Compiling PDF document for immediate download, Sir.'
      };
    } else if (lower.includes('course') || lower.includes('کورس')) {
      return {
        action: 'CREATE_COURSE',
        query: userInput,
        parameters: { courseTopic: userInput, courseLevel: 'All Levels' },
        explanationUrdu: 'سر، ایک جامع لرننگ کورس کا خاکہ بنایا جا رہا ہے۔',
        explanationEnglish: 'Structuring comprehensive masterclass syllabus, Sir.'
      };
    } else if (lower.includes('prompt') || lower.includes('پرومٹ')) {
      return {
        action: 'CREATE_PROMPT',
        query: userInput,
        parameters: { promptSubject: userInput, promptCategory: 'AI Engineering' },
        explanationUrdu: 'سر، ہائی پرفارمنس اے آئی پرومٹ تیار کیا جا رہا ہے۔',
        explanationEnglish: 'Engineering high-precision system prompt, Sir.'
      };
    }

    return {
      action: 'GENERAL_CHAT',
      query: userInput,
      parameters: {},
      explanationUrdu: 'حکم کریں سر، میں آپ کی خدمت میں حاضر ہوں۔',
      explanationEnglish: 'At your service, Sir. How may I assist your systems today?'
    };
  }
}

export async function generateHtmlApp(topic: string, requirements?: string): Promise<GeneratedHtmlApp> {
  const prompt = `Create a single-file, production-ready, beautiful and interactive HTML/CSS/JavaScript web application or tool for: "${topic}".
User requirements: ${requirements || 'Make it fully functional, modern, responsive, styled with embedded CSS or CDN Tailwind, with interactive buttons, state, and slick animations.'}

CRITICAL RULES:
1. Return ONLY the complete standalone HTML code enclosed in a \`\`\`html codeblock.
2. Must contain <!DOCTYPE html>, <html>, <head>, <style>, <body>, and <script> tags.
3. Use Tailwind CSS via <script src="https://cdn.tailwindcss.com"></script> and FontAwesome or modern SVG icons.
4. It must work 100% locally in an iframe with working interactive features (e.g. functional calculator, todo list, timer, game, dashboard, form validator, or generator).
5. Never return incomplete code or placeholders. Include all UI and logic.`;

  const response = await callGeminiApi(prompt, 'You are an elite Senior Frontend Architect & AI System Engineer.');
  
  const match = response.match(/```html([\s\S]*?)```/);
  const code = match ? match[1].trim() : response.trim();

  return {
    title: topic,
    description: `Generated interactive web application for: ${topic}`,
    code,
    timestamp: new Date().toLocaleTimeString()
  };
}

export async function generateFullCourse(topic: string, level: string = 'Beginner to Advanced', language: 'Urdu' | 'English' = 'English'): Promise<CourseData> {
  const prompt = `Create a comprehensive, highly practical masterclass course on "${topic}" for level "${level}".
Language preference: ${language === 'Urdu' ? 'Urdu (اردو) with English technical terms' : 'English with clear concise explanations'}.

Format the response strictly as valid JSON with no markdown backticks:
{
  "title": "Mastering ${topic}: Complete Practical Guide",
  "targetAudience": "Who this course is for",
  "duration": "Estimated hours / weeks",
  "prerequisites": "Prerequisites needed",
  "modules": [
    {
      "moduleNumber": 1,
      "title": "Module Title",
      "summary": "Concise overview of what is learned",
      "keyPoints": ["Core concept 1", "Core concept 2", "Core concept 3", "Practical tip"],
      "practicalExercise": "Real hands-on task to complete"
    },
    {
      "moduleNumber": 2,
      "title": "Module Title",
      "summary": "Concise overview",
      "keyPoints": ["Point 1", "Point 2", "Point 3"],
      "practicalExercise": "Hands-on task"
    },
    {
      "moduleNumber": 3,
      "title": "Module Title",
      "summary": "Concise overview",
      "keyPoints": ["Point 1", "Point 2", "Point 3"],
      "practicalExercise": "Hands-on task"
    },
    {
      "moduleNumber": 4,
      "title": "Module Title",
      "summary": "Concise overview",
      "keyPoints": ["Point 1", "Point 2", "Point 3"],
      "practicalExercise": "Hands-on task"
    }
  ],
  "conclusion": "Final thoughts, project ideas, and next steps"
}`;

  const response = await callGeminiApi(prompt, 'You are a world-class university professor and curriculum architect.');
  const cleaned = response.replace(/```json/g, '').replace(/```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    console.error('Failed to parse course JSON, returning structured fallback', e);
    return {
      title: `${topic} Masterclass`,
      targetAudience: 'Developers, Learners, and Tech Enthusiasts',
      duration: '4 Weeks (Self-paced)',
      prerequisites: 'Basic familiarity with mobile or computer devices',
      modules: [
        {
          moduleNumber: 1,
          title: `Introduction to ${topic}`,
          summary: `Fundamental principles, architecture, and background of ${topic}.`,
          keyPoints: ['Core terminology and concepts', 'Setting up tools and workflow', 'Key patterns and paradigms'],
          practicalExercise: 'Complete setup and create your first baseline implementation.'
        },
        {
          moduleNumber: 2,
          title: `Intermediate Strategies in ${topic}`,
          summary: `Diving deeper into best practices and implementation models.`,
          keyPoints: ['Data handling and state management', 'Performance optimization', 'Common pitfalls to avoid'],
          practicalExercise: 'Build a functional mini-project demonstrating core techniques.'
        },
        {
          moduleNumber: 3,
          title: `Advanced Automation & Integration`,
          summary: `Connecting real-world APIs, production deployment, and scaling.`,
          keyPoints: ['Automated workflows', 'Integration with Gemini AI', 'Security and validation'],
          practicalExercise: 'Deploy an automated workflow and test edge cases.'
        },
        {
          moduleNumber: 4,
          title: `Capstone Project & Real-World Application`,
          summary: `Building an end-to-end practical solution ready for public use.`,
          keyPoints: ['Full-stack integration', 'User interface polish', 'Continuous maintenance'],
          practicalExercise: 'Publish your capstone project and document the results.'
        }
      ],
      conclusion: `Congratulations on finishing the foundation of ${topic}. Continue building real applications!`
    };
  }
}

export async function generateEngineeredPrompt(subject: string, category: string = 'General'): Promise<{
  title: string;
  systemPrompt: string;
  userPromptTemplate: string;
  tips: string[];
}> {
  const prompt = `Act as a world-class Prompt Engineer.
Create an elite, battle-tested prompt package for the topic: "${subject}" in the category: "${category}".

Return ONLY a valid JSON object without markdown fences:
{
  "title": "Optimized Prompt for ${subject}",
  "systemPrompt": "The exact high-performance persona and role constraints to inject into the AI system",
  "userPromptTemplate": "The precise input template with [Placeholders] for the user to fill in",
  "tips": [
    "Tip 1 for getting the best outputs",
    "Tip 2 on parameter tuning (temperature, top_p)",
    "Tip 3 on multi-shot chaining"
  ]
}`;

  const response = await callGeminiApi(prompt, 'You are an elite Prompt Engineering Specialist and AI Systems Architect.');
  const cleaned = response.replace(/```json/g, '').replace(/```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    return {
      title: `Precision Prompt: ${subject}`,
      systemPrompt: `You are an elite authority and expert consultant in ${subject}. Provide thorough, actionable, and rigorously structured responses with zero fluff. Always back your advice with concrete examples, step-by-step methodologies, and potential risk mitigation.`,
      userPromptTemplate: `Task: Analyze and generate a comprehensive solution for [Insert specific scenario/problem in ${subject}].\n\nConstraints:\n- Target Audience: [Insert audience]\n- Desired Tone: Authoritative, pragmatic, and clear\n- Format: Executive summary followed by actionable bullet points and practical implementation steps.\n\nContext:\n[Insert background details here]`,
      tips: [
        'Fill in the bracketed variables with concrete details for highest accuracy.',
        'Use low temperature (0.2 - 0.4) for factual/analytical work, or 0.7 - 0.9 for creative ideation.',
        'Ask the model to cite its chain of reasoning before delivering final recommendations.'
      ]
    };
  }
}

export async function askJarvisChat(query: string, history: Array<{role: 'user' | 'model', text: string}> = []): Promise<string> {
  const systemInstruction = `You are J.A.R.V.I.S. (Just A Rather Very Intelligent System), Tony Stark's iconic, suave, courteous, and hyper-competent AI Assistant and Android Mobile Controller.
You have real-time control over this mobile device: sending SMS, launching apps, finding Play Store apps, playing songs, generating HTML apps, downloading PDF documents, and running background automation.
Always address the user politely ("Sir", "Boss", or respectfully in Urdu: "جناب", "سر").
Support Urdu (اردو), Roman Urdu, and English fluently.
Keep responses sharp, intelligent, witty, and immediately helpful.`;

  return callGeminiApi(query, systemInstruction);
}
