import React, { useState } from 'react';
import { 
  MessageSquare, 
  Smartphone, 
  Download, 
  Music, 
  Code, 
  FileText, 
  Layers, 
  ExternalLink, 
  Play,
  Send,
  Search,
  CheckCircle2,
  Sparkles
} from 'lucide-react';
import { KNOWN_PHONE_APPS } from '../services/phoneController';

interface PhoneControlPanelProps {
  onSendSms: (phone: string, msg: string) => void;
  onOpenApp: (appName: string) => void;
  onInstallApp: (appName: string) => void;
  onPlaySong: (title: string) => void;
  onGenerateHtml: (topic: string) => void;
  onDownloadPdf: (title: string, content: string) => void;
}

export const PhoneControlPanel: React.FC<PhoneControlPanelProps> = ({
  onSendSms,
  onOpenApp,
  onInstallApp,
  onPlaySong,
  onGenerateHtml,
  onDownloadPdf
}) => {
  const [activeTab, setActiveTab] = useState<'ACTIONS' | 'APPS' | 'MEDIA' | 'DEVELOPER'>('ACTIONS');

  // SMS Form state
  const [smsPhone, setSmsPhone] = useState('');
  const [smsText, setSmsText] = useState('سلام، میں جلد پہنچ رہا ہوں۔');
  
  // App search
  const [appSearch, setAppSearch] = useState('');
  
  // Song search
  const [songQuery, setSongQuery] = useState('Atif Aslam Dil Diyan Gallan');

  // PDF Form
  const [pdfTitle, setPdfTitle] = useState('System Intelligence Report');
  const [pdfContent, setPdfContent] = useState('This is an autonomous document generated by J.A.R.V.I.S. featuring device telemetry, real-time analytics, and task execution logs.');

  // HTML Quick Builder
  const [htmlTopic, setHtmlTopic] = useState('Smart Weather & Clock Widget');

  const filteredApps = KNOWN_PHONE_APPS.filter(a => 
    a.name.toLowerCase().includes(appSearch.toLowerCase()) || 
    a.category.toLowerCase().includes(appSearch.toLowerCase())
  );

  return (
    <div className="sci-fi-box rounded-xl p-4 md:p-6 w-full text-jarvis-text">
      {/* Header with Switcher */}
      <div className="flex flex-wrap items-center justify-between border-b border-jarvis-border pb-3 mb-4 gap-2">
        <div className="flex items-center gap-2">
          <Smartphone className="w-5 h-5 text-jarvis-cyan animate-pulse" />
          <h2 className="font-orbitron text-sm md:text-base font-bold tracking-wider text-cyan-200">
            DEVICE CONTROLLER HUB
          </h2>
          <span className="text-[10px] bg-jarvis-cyan/20 text-jarvis-cyan px-2 py-0.5 rounded border border-jarvis-cyan/30">
            REAL-TIME
          </span>
        </div>

        <div className="flex items-center gap-1 bg-jarvis-surface p-1 rounded-lg border border-jarvis-border text-xs font-mono-tech">
          {(['ACTIONS', 'APPS', 'MEDIA', 'DEVELOPER'] as const).map(tab => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-3 py-1 rounded transition-all ${
                activeTab === tab
                  ? 'bg-jarvis-cyan text-black font-bold shadow-cyan-glow'
                  : 'text-cyan-300/70 hover:text-cyan-100 hover:bg-jarvis-card'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      {/* Tab 1: ACTIONS (SMS, App Search, Play Store) */}
      {activeTab === 'ACTIONS' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* SMS Dispatcher */}
          <div className="bg-jarvis-card/60 p-4 rounded-lg border border-jarvis-border/80 flex flex-col justify-between">
            <div>
              <div className="flex items-center gap-2 mb-2 text-cyan-300 font-orbitron text-xs">
                <MessageSquare className="w-4 h-4 text-jarvis-cyan" />
                <span>SMS DISPATCH PROTOCOL</span>
              </div>
              <p className="text-xs text-slate-300 mb-3">
                Send an SMS directly to any contact or phone number.
              </p>

              <div className="space-y-2">
                <input
                  type="tel"
                  placeholder="Phone Number / Contact (e.g. 03001234567)"
                  value={smsPhone}
                  onChange={e => setSmsPhone(e.target.value)}
                  className="w-full bg-jarvis-surface border border-jarvis-border px-3 py-1.5 rounded text-sm text-cyan-100 focus:outline-none focus:border-jarvis-cyan font-mono-tech"
                />
                <textarea
                  placeholder="Message body / میسج لکھیں"
                  rows={2}
                  value={smsText}
                  onChange={e => setSmsText(e.target.value)}
                  className="w-full bg-jarvis-surface border border-jarvis-border px-3 py-1.5 rounded text-sm text-cyan-100 focus:outline-none focus:border-jarvis-cyan"
                />
              </div>
            </div>

            <button
              onClick={() => onSendSms(smsPhone, smsText)}
              className="mt-3 w-full bg-jarvis-cyan hover:bg-cyan-300 text-black font-orbitron font-bold text-xs py-2 px-4 rounded flex items-center justify-center gap-2 transition-all shadow-cyan-glow"
            >
              <Send className="w-3.5 h-3.5" />
              <span>DISPATCH SMS (رئیل ایس ایم ایس)</span>
            </button>
          </div>

          {/* Google Play Store Installer */}
          <div className="bg-jarvis-card/60 p-4 rounded-lg border border-jarvis-border/80 flex flex-col justify-between">
            <div>
              <div className="flex items-center gap-2 mb-2 text-cyan-300 font-orbitron text-xs">
                <Download className="w-4 h-4 text-jarvis-amber" />
                <span>PLAY STORE APP INSTALLER</span>
              </div>
              <p className="text-xs text-slate-300 mb-3">
                Download and install applications directly from Google Play.
              </p>

              <div className="space-y-2">
                <div className="relative">
                  <Search className="w-4 h-4 text-cyan-400 absolute left-3 top-2.5" />
                  <input
                    type="text"
                    placeholder="App Name (e.g. WhatsApp, CapCut, Instagram)"
                    value={appSearch}
                    onChange={e => setAppSearch(e.target.value)}
                    className="w-full bg-jarvis-surface border border-jarvis-border pl-9 pr-3 py-1.5 rounded text-sm text-cyan-100 focus:outline-none focus:border-jarvis-cyan"
                  />
                </div>

                <div className="flex flex-wrap gap-1.5 pt-1">
                  {['CapCut', 'WhatsApp', 'PUBG Mobile', 'Canva', 'Telegram'].map(suggested => (
                    <button
                      key={suggested}
                      onClick={() => setAppSearch(suggested)}
                      className="text-[11px] bg-jarvis-surface hover:bg-cyan-950 px-2 py-0.5 rounded border border-cyan-800 text-cyan-300"
                    >
                      +{suggested}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <button
              onClick={() => onInstallApp(appSearch || 'WhatsApp')}
              className="mt-3 w-full bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 hover:to-amber-400 text-black font-orbitron font-bold text-xs py-2 px-4 rounded flex items-center justify-center gap-2 transition-all shadow-md"
            >
              <Download className="w-3.5 h-3.5" />
              <span>INSTALL FROM PLAY STORE (انسٹال کرو)</span>
            </button>
          </div>
        </div>
      )}

      {/* Tab 2: APPS LAUNCHER */}
      {activeTab === 'APPS' && (
        <div>
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs text-cyan-300/80 font-mono-tech">
              INSTALLED PHONE APPLICATIONS MATRIX ({filteredApps.length})
            </span>
            <input
              type="text"
              placeholder="Filter apps..."
              value={appSearch}
              onChange={e => setAppSearch(e.target.value)}
              className="bg-jarvis-surface border border-jarvis-border px-3 py-1 rounded text-xs text-cyan-100 focus:outline-none focus:border-jarvis-cyan w-40"
            />
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-2.5 max-h-72 overflow-y-auto pr-1">
            {filteredApps.map(app => (
              <button
                key={app.name}
                onClick={() => onOpenApp(app.name)}
                className="group flex flex-col items-center justify-center p-3 rounded-lg bg-jarvis-surface/90 hover:bg-jarvis-cyan/15 border border-jarvis-border hover:border-jarvis-cyan transition-all text-center relative overflow-hidden"
              >
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-900 to-slate-900 flex items-center justify-center mb-2 group-hover:scale-110 transition-transform shadow-inner border border-cyan-500/30">
                  <ExternalLink className="w-5 h-5 text-jarvis-cyan" />
                </div>
                <span className="text-xs font-semibold text-slate-200 group-hover:text-cyan-200 truncate w-full">
                  {app.name}
                </span>
                <span className="text-[10px] text-cyan-500 font-mono-tech mt-0.5">
                  {app.category}
                </span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Tab 3: MEDIA / SONG PLAYER */}
      {activeTab === 'MEDIA' && (
        <div className="bg-jarvis-card/60 p-4 rounded-lg border border-jarvis-border/80">
          <div className="flex items-center gap-2 mb-2 text-cyan-300 font-orbitron text-xs">
            <Music className="w-4 h-4 text-jarvis-green" />
            <span>JARVIS AUDIO & MUSIC STREAMING</span>
          </div>
          <p className="text-xs text-slate-300 mb-3">
            Ask Jarvis to play any track, qawwali, song, or playlist on your phone.
          </p>

          <div className="flex flex-col sm:flex-row gap-2 mb-3">
            <input
              type="text"
              placeholder="Song title or artist (e.g. Atif Aslam, Coke Studio, Lo-fi Beats)"
              value={songQuery}
              onChange={e => setSongQuery(e.target.value)}
              className="flex-1 bg-jarvis-surface border border-jarvis-border px-3 py-2 rounded text-sm text-cyan-100 focus:outline-none focus:border-jarvis-cyan"
            />
            <button
              onClick={() => onPlaySong(songQuery)}
              className="bg-jarvis-green hover:bg-emerald-400 text-black font-orbitron font-bold text-xs py-2 px-5 rounded flex items-center justify-center gap-2 shadow-md transition-all"
            >
              <Play className="w-4 h-4 fill-current" />
              <span>PLAY NOW (سونگ چلاؤ)</span>
            </button>
          </div>

          <div className="flex flex-wrap gap-2 pt-1">
            <span className="text-xs text-cyan-400/80 self-center font-mono-tech">Quick Picks:</span>
            {[
              'Coke Studio Season 14 Tu Jhoom',
              'Nusrat Fateh Ali Khan Qawwali',
              'Iron Man AC/DC Back in Black',
              'Arijit Singh Best Songs',
              'Cyberpunk Synthwave 2026'
            ].map(pick => (
              <button
                key={pick}
                onClick={() => {
                  setSongQuery(pick);
                  onPlaySong(pick);
                }}
                className="text-xs bg-jarvis-surface hover:bg-cyan-950 px-2.5 py-1 rounded border border-cyan-800 text-cyan-300 flex items-center gap-1"
              >
                <Play className="w-3 h-3 fill-current text-jarvis-green" />
                <span>{pick}</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Tab 4: DEVELOPER (PDF & HTML Generator) */}
      {activeTab === 'DEVELOPER' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Real PDF Generator */}
          <div className="bg-jarvis-card/60 p-4 rounded-lg border border-jarvis-border/80 flex flex-col justify-between">
            <div>
              <div className="flex items-center gap-2 mb-2 text-cyan-300 font-orbitron text-xs">
                <FileText className="w-4 h-4 text-jarvis-cyan" />
                <span>NATIVE PDF GENERATOR & DOWNLOADER</span>
              </div>
              <p className="text-xs text-slate-300 mb-2">
                Compiles real PDF files with Jarvis headers and downloads directly to your device.
              </p>

              <div className="space-y-2">
                <input
                  type="text"
                  placeholder="Document Title"
                  value={pdfTitle}
                  onChange={e => setPdfTitle(e.target.value)}
                  className="w-full bg-jarvis-surface border border-jarvis-border px-3 py-1.5 rounded text-sm text-cyan-100 focus:outline-none focus:border-jarvis-cyan"
                />
                <textarea
                  placeholder="Document content..."
                  rows={2}
                  value={pdfContent}
                  onChange={e => setPdfContent(e.target.value)}
                  className="w-full bg-jarvis-surface border border-jarvis-border px-3 py-1.5 rounded text-sm text-cyan-100 focus:outline-none focus:border-jarvis-cyan"
                />
              </div>
            </div>

            <button
              onClick={() => onDownloadPdf(pdfTitle, pdfContent)}
              className="mt-3 w-full bg-jarvis-cyan hover:bg-cyan-300 text-black font-orbitron font-bold text-xs py-2 px-4 rounded flex items-center justify-center gap-2 transition-all shadow-cyan-glow"
            >
              <Download className="w-3.5 h-3.5" />
              <span>DOWNLOAD PDF (پی ڈی ایف ڈاؤنلوڈ کرو)</span>
            </button>
          </div>

          {/* HTML App Generator Trigger */}
          <div className="bg-jarvis-card/60 p-4 rounded-lg border border-jarvis-border/80 flex flex-col justify-between">
            <div>
              <div className="flex items-center gap-2 mb-2 text-cyan-300 font-orbitron text-xs">
                <Code className="w-4 h-4 text-purple-400" />
                <span>HTML WEB APP BUILDER (GEMINI PRO)</span>
              </div>
              <p className="text-xs text-slate-300 mb-2">
                Generates responsive HTML/CSS/JS applications ready for instant execution.
              </p>

              <div className="space-y-2">
                <input
                  type="text"
                  placeholder="App Idea (e.g. Scientific Calculator, To-Do Board)"
                  value={htmlTopic}
                  onChange={e => setHtmlTopic(e.target.value)}
                  className="w-full bg-jarvis-surface border border-jarvis-border px-3 py-1.5 rounded text-sm text-cyan-100 focus:outline-none focus:border-purple-400"
                />
                <div className="flex flex-wrap gap-1">
                  {['Expense Tracker', 'Retro Snake Game', 'Pomodoro Timer'].map(idea => (
                    <button
                      key={idea}
                      onClick={() => setHtmlTopic(idea)}
                      className="text-[10px] bg-jarvis-surface px-2 py-0.5 rounded border border-purple-800 text-purple-300"
                    >
                      {idea}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <button
              onClick={() => onGenerateHtml(htmlTopic)}
              className="mt-3 w-full bg-gradient-to-r from-purple-500 to-indigo-500 hover:from-purple-400 hover:to-indigo-400 text-white font-orbitron font-bold text-xs py-2 px-4 rounded flex items-center justify-center gap-2 transition-all shadow-md"
            >
              <Sparkles className="w-3.5 h-3.5 text-yellow-300" />
              <span>BUILD HTML APP (ایچ ٹی ایم ایل بناؤ)</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
